name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        # We just added another step and relative path of the custom action
      - name: Load & Cache Dependencies
        uses: ./.github/actions/cached-deps

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build application(simulates the deploy)
        run: npm run build
